export interface Ville {
  slug: string;
  name: string;
  dept: string;
  depName: string;
  context: string;
  faqQ: string;
  faqA: string;
}

export const VILLES: Ville[] = [
  // ─── Paris intramuros (arrondissements) — cœur de marché ClimExpert ──────────
  {
    slug: "paris-1",
    name: "Paris 1er",
    dept: "75",
    depName: "Paris",
    context: "Au cœur historique de la capitale (Louvre, Châtelet, Les Halles), le 1er arrondissement est un secteur hyper-central, très protégé sur le plan patrimonial. Les immeubles anciens y côtoient de nombreux commerces et bureaux. Toute installation de climatisation y exige une grande discrétion : pose de l'unité extérieure en cour intérieure ou en toiture non visible.",
    faqQ: "Peut-on installer une climatisation dans le 1er arrondissement malgré les contraintes patrimoniales ?",
    faqA: "Oui, mais le 1er est en grande partie en secteur protégé (PSMV / abords de monuments). Une installation visible depuis la voie publique nécessite l'accord de l'Architecte des Bâtiments de France. En pratique, nous privilégions une pose en cour ou sur toiture cachée. Un diagnostic préalable de votre adresse est réalisé avant tout devis.",
  },
  {
    slug: "paris-2",
    name: "Paris 2e",
    dept: "75",
    depName: "Paris",
    context: "Le plus petit arrondissement de Paris (Bourse, Sentier, Montorgueil) est dense et très actif, avec une forte concentration de locaux professionnels — mode, agences, sociétés tech. Le bâti, principalement ancien, impose des installations soignées. Nous intervenons aussi bien pour des bureaux que pour les appartements au-dessus des commerces.",
    faqQ: "Faites-vous l'installation de climatisation pour les bureaux du 2e arrondissement ?",
    faqA: "Oui, le 2e concentre beaucoup de locaux professionnels. Nous installons des systèmes multisplit ou des cassettes plafonnières adaptés aux open spaces et commerces, avec une mise en service hors heures d'ouverture si besoin. Un devis gratuit est établi sous 24h après visite technique.",
  },
  {
    slug: "paris-3",
    name: "Paris 3e",
    dept: "75",
    depName: "Paris",
    context: "Le 3e, qui couvre le Haut-Marais et le quartier des Arts-et-Métiers, mêle immeubles anciens de caractère, galeries et locaux professionnels. Une partie de l'arrondissement est en secteur protégé du Marais. La climatisation réversible y est très demandée, notamment pour les ateliers reconvertis et les lofts.",
    faqQ: "Le Marais étant protégé, comment se passe une installation dans le 3e ?",
    faqA: "Une partie du 3e relève du plan de sauvegarde du Marais. Les unités extérieures visibles depuis la rue y sont très encadrées : nous les implantons en cour intérieure ou en façade arrière. Nos techniciens connaissent ces contraintes et vous accompagnent dans les démarches auprès de la mairie et de l'ABF.",
  },
  {
    slug: "paris-4",
    name: "Paris 4e",
    dept: "75",
    depName: "Paris",
    context: "Le 4e (Marais, Île Saint-Louis, Hôtel de Ville) est l'un des secteurs les plus protégés de Paris, avec un bâti historique exceptionnel. Les installations de climatisation y sont particulièrement contraintes et demandent un vrai savoir-faire pour rester invisibles. Les solutions gainables et les poses en cour sont privilégiées.",
    faqQ: "Est-il possible de climatiser un appartement ancien dans le 4e (Marais / Île Saint-Louis) ?",
    faqA: "Oui, même dans le bâti historique du 4e. La difficulté est l'esthétique et l'accord ABF en secteur sauvegardé : nous proposons des solutions discrètes (gainable, unité en cour, liaisons cachées). Chaque projet démarre par un diagnostic sur place pour valider la faisabilité avant devis.",
  },
  {
    slug: "paris-5",
    name: "Paris 5e",
    dept: "75",
    depName: "Paris",
    context: "Le Quartier Latin (Panthéon, Sorbonne, Mouffetard) est un arrondissement ancien et vallonné, marqué par les studios et petites surfaces étudiantes ainsi que de beaux appartements de caractère. Les immeubles anciens, souvent sans ascenseur, demandent une organisation de chantier rigoureuse. Le monosplit mural y est la solution la plus fréquente.",
    faqQ: "Quel système de climatisation pour un petit appartement dans le 5e ?",
    faqA: "Pour un studio ou un deux-pièces du 5e, un monosplit mural réversible suffit généralement (à partir de 1 500 € TTC, pose incluse). Il rafraîchit l'été et fait chauffage d'appoint l'hiver. Pour les surfaces plus grandes ou plusieurs pièces, on s'oriente vers un multisplit. Devis gratuit après visite technique.",
  },
  {
    slug: "paris-6",
    name: "Paris 6e",
    dept: "75",
    depName: "Paris",
    context: "Saint-Germain-des-Prés, Odéon, le jardin du Luxembourg : le 6e est un arrondissement haussmannien prestigieux où l'exigence esthétique est forte. Le bâti ancien et la proximité de monuments imposent souvent des contraintes ABF. Nous y réalisons des installations très discrètes, gainables ou multisplits soignés.",
    faqQ: "Comment garantir une installation discrète dans le 6e arrondissement ?",
    faqA: "Dans le 6e, nous privilégions les systèmes gainables (diffuseurs encastrés, aucune unité visible à l'intérieur) et l'implantation de l'unité extérieure en cour ou sur toiture cachée. En secteur ABF, nous validons la faisabilité avant tout engagement. L'objectif : un confort total sans dénaturer votre intérieur.",
  },
  {
    slug: "paris-7",
    name: "Paris 7e",
    dept: "75",
    depName: "Paris",
    context: "Le 7e (Tour Eiffel, Invalides, Gros-Caillou) est un arrondissement résidentiel de prestige, riche en immeubles haussmanniens et hôtels particuliers. La proximité de monuments majeurs y rend les contraintes ABF fréquentes. Les grandes surfaces se prêtent aux installations gainables invisibles, exigeant une finition irréprochable.",
    faqQ: "Une autorisation ABF est-elle nécessaire pour climatiser dans le 7e ?",
    faqA: "Très souvent, oui : une grande partie du 7e est en abords de monuments historiques. Toute unité visible depuis l'espace public requiert l'accord de l'Architecte des Bâtiments de France. Nous étudions chaque adresse et privilégions des poses non visibles (cour, toiture) pour faciliter l'acceptation.",
  },
  {
    slug: "paris-8",
    name: "Paris 8e",
    dept: "75",
    depName: "Paris",
    context: "Champs-Élysées, Madeleine, Monceau : le 8e est l'arrondissement des bureaux, sièges sociaux, hôtels et hôtels particuliers. La demande y est forte côté tertiaire (climatisation de bureaux et commerces) comme résidentiel haut de gamme. Nous installons aussi bien des cassettes plafonnières pour locaux pro que des systèmes gainables pour les grands appartements.",
    faqQ: "Installez-vous la climatisation des bureaux et commerces du 8e ?",
    faqA: "Oui. Le 8e est un pôle tertiaire majeur. Nous équipons bureaux, boutiques et restaurants en cassettes plafonnières ou systèmes multisplit dimensionnés selon la surface et l'occupation. La mise en service peut se faire en dehors des horaires d'ouverture. Devis professionnel gratuit sous 24h.",
  },
  {
    slug: "paris-9",
    name: "Paris 9e",
    dept: "75",
    depName: "Paris",
    context: "Le 9e (Opéra, Grands Boulevards, SoPi) est un arrondissement mixte, à la fois résidentiel et tertiaire, dominé par les immeubles haussmanniens en copropriété dense. La forte minéralisation et l'effet d'îlot de chaleur y rendent la climatisation réversible très recherchée. Nous intervenons dans les appartements comme dans les bureaux du secteur.",
    faqQ: "Faut-il l'accord de la copropriété pour une clim dans le 9e ?",
    faqA: "Oui, dans le bâti haussmannien du 9e, la pose d'une unité extérieure en façade ou sur cour commune nécessite l'accord de l'assemblée générale de copropriété. Nous vous fournissons un dossier technique (plans, photomontage) pour faciliter le vote en AG, et privilégions les emplacements les moins visibles.",
  },
  {
    slug: "paris-10",
    name: "Paris 10e",
    dept: "75",
    depName: "Paris",
    context: "Entre les gares du Nord et de l'Est et le Canal Saint-Martin, le 10e est un arrondissement populaire et animé, riche en immeubles faubouriens et en restaurants. La restauration y génère une forte demande de climatisation pour le confort des salles. Nous équipons aussi bien les logements que les commerces de bouche du quartier.",
    faqQ: "Pouvez-vous climatiser un restaurant ou un commerce dans le 10e ?",
    faqA: "Oui, c'est une demande fréquente dans le 10e. Pour un restaurant, nous dimensionnons le système selon la surface, l'affluence et les apports de chaleur (cuisine, vitrines). Cassette plafonnière ou multisplit selon la configuration, avec une pose qui respecte les contraintes de la copropriété et de la voirie.",
  },
  {
    slug: "paris-11",
    name: "Paris 11e",
    dept: "75",
    depName: "Paris",
    context: "L'un des arrondissements les plus peuplés et les plus animés de Paris (Bastille, République, Oberkampf), le 11e est très dense, mêlant immeubles faubouriens, logements et une vie nocturne intense. Les appartements, souvent mal isolés et orientés rue, souffrent fortement de la chaleur estivale. La climatisation réversible y est l'une des plus demandées de la capitale.",
    faqQ: "Combien de temps pour installer une climatisation dans le 11e ?",
    faqA: "Dans le 11e, une installation monosplit prend une demi-journée, un multisplit 2 ou 3 pièces une journée complète. Nous intervenons généralement sous 48h après acceptation du devis. La principale étape préalable reste, en copropriété, l'accord de l'AG pour l'unité extérieure : nous vous aidons à le préparer.",
  },
  {
    slug: "paris-12",
    name: "Paris 12e",
    dept: "75",
    depName: "Paris",
    context: "Le 12e (Nation, Bercy, Daumesnil) est un arrondissement résidentiel et familial, qui combine immeubles anciens, copropriétés des années 70 et programmes récents comme la ZAC de Bercy. Plus aéré que le centre, il offre davantage de souplesse pour l'implantation des unités extérieures (balcons, cours, terrasses). La demande y est soutenue côté familles et locaux professionnels.",
    faqQ: "Quelles solutions de climatisation pour un appartement familial dans le 12e ?",
    faqA: "Pour un logement familial du 12e (3 pièces et plus), le multisplit est idéal : une unité extérieure alimente plusieurs pièces (séjour, chambres) avec un réglage indépendant. Comptez à partir de 2 800 € TTC pour 2 pièces, 3 800 € pour 3 pièces. Les balcons et cours du 12e facilitent souvent la pose de l'unité extérieure.",
  },
  {
    slug: "paris-13",
    name: "Paris 13e",
    dept: "75",
    depName: "Paris",
    context: "Le 13e (Place d'Italie, Tolbiac, Quartier asiatique) se distingue par ses tours résidentielles des années 70, souvent peu performantes thermiquement, et par le quartier moderne de Paris Rive Gauche. Les appartements en étage élevé y subissent fortement la surchauffe estivale. La climatisation réversible y améliore nettement le confort et la valeur du bien.",
    faqQ: "Peut-on installer une climatisation dans une tour des années 70 du 13e ?",
    faqA: "Oui. Les tours du 13e sont d'excellentes candidates : mal isolées, elles surchauffent l'été. L'installation demande l'accord de la copropriété pour l'unité extérieure (façade ou balcon) et un passage de liaisons soigné. Nous réalisons régulièrement ce type de chantier et gérons les contraintes propres aux immeubles de grande hauteur.",
  },
  {
    slug: "paris-14",
    name: "Paris 14e",
    dept: "75",
    depName: "Paris",
    context: "Le 14e (Montparnasse, Alésia, Denfert-Rochereau) est un arrondissement résidentiel et plutôt calme, mêlant immeubles haussmanniens, constructions des années 1930 et petites copropriétés. La demande de climatisation y est régulière, surtout pour les appartements sous combles et orientés sud. Nous y réalisons monosplits et multisplits discrets.",
    faqQ: "Les appartements sous toit du 14e peuvent-ils être climatisés efficacement ?",
    faqA: "Oui, et c'est même très recommandé : les derniers étages et combles du 14e surchauffent fortement l'été. Une climatisation réversible bien dimensionnée rétablit le confort. Nous étudions l'isolation et l'orientation lors de la visite technique pour choisir la puissance adaptée et l'emplacement optimal de l'unité extérieure.",
  },
  {
    slug: "paris-15",
    name: "Paris 15e",
    dept: "75",
    depName: "Paris",
    context: "Arrondissement le plus peuplé de Paris (Commerce, Vaugirard, Front de Seine), le 15e est un secteur résidentiel et familial, avec un parc immobilier mêlant haussmannien, immeubles des années 60-70 et tours du Front de Seine. C'est notre arrondissement d'origine : nos techniciens y interviennent en priorité, avec des délais particulièrement courts. La demande de climatisation y est l'une des plus fortes de la capitale.",
    faqQ: "ClimExpert intervient-il rapidement dans le 15e arrondissement ?",
    faqA: "Oui, le 15e est notre arrondissement d'implantation : nos techniciens y interviennent en priorité, souvent sous 48h voire plus vite en dépannage. Que vous soyez dans le bâti haussmannien autour de Commerce ou dans les tours du Front de Seine, nous connaissons parfaitement les contraintes locales. Devis gratuit sous 24h.",
  },
  {
    slug: "paris-16",
    name: "Paris 16e",
    dept: "75",
    depName: "Paris",
    context: "Passy, Auteuil, Trocadéro : le 16e est l'arrondissement des beaux quartiers, riche en immeubles haussmanniens, en bâtiments Art déco et en grandes surfaces. L'exigence esthétique y est élevée et les abords du Trocadéro relèvent souvent de contraintes ABF. Les multisplits sur mesure et les installations gainables invisibles y sont privilégiés.",
    faqQ: "Quelle climatisation pour un grand appartement haussmannien du 16e ?",
    faqA: "Pour les grandes surfaces du 16e, deux options : le multisplit (plusieurs unités murales discrètes reliées à un seul groupe extérieur) ou le gainable (diffuseurs encastrés, totalement invisible). Le gainable est idéal pour préserver le cachet haussmannien. En zone ABF (Trocadéro), nous validons la faisabilité avant devis.",
  },
  {
    slug: "paris-17",
    name: "Paris 17e",
    dept: "75",
    depName: "Paris",
    context: "Le 17e est un arrondissement contrasté : les quartiers bourgeois de Monceau et des Ternes, au bâti haussmannien cossu, côtoient les Batignolles et l'éco-quartier Clichy-Batignolles, en plein renouveau. Cette diversité se traduit par des projets variés, du grand appartement ancien au logement neuf. La climatisation réversible y est de plus en plus standard.",
    faqQ: "Les logements neufs de Clichy-Batignolles (17e) sont-ils adaptés à la climatisation ?",
    faqA: "Oui, les programmes neufs de Clichy-Batignolles facilitent souvent l'installation (emplacements prévus, meilleure isolation). Pour le bâti haussmannien des Ternes ou de Monceau, on s'adapte avec des solutions discrètes et l'accord de copropriété. Dans les deux cas, la visite technique gratuite permet de définir la meilleure configuration.",
  },
  {
    slug: "paris-18",
    name: "Paris 18e",
    dept: "75",
    depName: "Paris",
    context: "Le 18e (Montmartre, Barbès, La Goutte d'Or) est un arrondissement de fort contraste, entre la Butte Montmartre, secteur protégé et vallonné, et des quartiers populaires très denses. Les immeubles anciens y dominent. Les contraintes patrimoniales autour de Montmartre demandent des installations discrètes, tandis que le reste de l'arrondissement offre plus de souplesse.",
    faqQ: "Peut-on installer une climatisation à Montmartre (18e) malgré la zone protégée ?",
    faqA: "Oui, mais le secteur de la Butte Montmartre est protégé : les unités visibles depuis la rue sont encadrées et peuvent nécessiter un accord ABF. Nous privilégions une pose en cour ou en façade arrière non visible. Hors du périmètre protégé, l'installation suit les règles classiques de copropriété. Un diagnostic préalable lève les doutes.",
  },
  {
    slug: "paris-19",
    name: "Paris 19e",
    dept: "75",
    depName: "Paris",
    context: "Le 19e (Buttes-Chaumont, La Villette, Stalingrad) est un arrondissement populaire en pleine valorisation, qui mêle grands ensembles, immeubles anciens et nombreux programmes neufs le long du bassin de la Villette et du canal de l'Ourcq. Cette diversité de bâti permet des installations variées, du logement social rénové à l'appartement neuf bien isolé.",
    faqQ: "Une climatisation réversible est-elle un bon investissement dans le 19e ?",
    faqA: "Oui. Dans un arrondissement en valorisation comme le 19e, la climatisation réversible améliore le confort été comme hiver (chauffage d'appoint) et augmente l'attractivité du bien à la location comme à la revente. Pour les logements anciens peu isolés, le gain de confort est immédiat. Devis gratuit après visite technique.",
  },
  {
    slug: "paris-20",
    name: "Paris 20e",
    dept: "75",
    depName: "Paris",
    context: "Ménilmontant, Belleville, Père-Lachaise : le 20e est un arrondissement populaire et créatif, en pleine valorisation, au bâti faubourien et vallonné. Les appartements anciens, souvent mal isolés, y supportent difficilement les fortes chaleurs. La climatisation réversible y répond à une double attente : rafraîchir l'été et compléter le chauffage l'hiver.",
    faqQ: "Quel budget pour climatiser un appartement ancien dans le 20e ?",
    faqA: "Dans le 20e, comptez à partir de 1 500 € TTC pour un monosplit (une pièce) et 2 800 € TTC pour un multisplit 2 pièces, pose et mise en service incluses. Les immeubles faubouriens demandent parfois un soin particulier pour le passage des liaisons. Le devis précis est établi gratuitement lors de la visite technique.",
  },
  {
    slug: "boulogne-billancourt",
    name: "Boulogne-Billancourt",
    dept: "92",
    depName: "Hauts-de-Seine",
    context: "Première ville des Hauts-de-Seine avec plus de 120 000 habitants, Boulogne-Billancourt est une commune dense composée majoritairement d'appartements en copropriété. Les étés caniculaires y sont particulièrement ressentis dans les appartements orientés sud et ouest. Nos techniciens interviennent régulièrement dans les immeubles haussmanniens et les résidences récentes du quartier Trapèze.",
    faqQ: "Faut-il l'accord de la copropriété pour installer une clim à Boulogne-Billancourt ?",
    faqA: "À Boulogne-Billancourt, comme dans toute copropriété, l'accord de l'assemblée générale est nécessaire si l'unité extérieure est posée en façade ou sur une partie commune. Pour les balcons privatifs, une déclaration préalable de travaux auprès de la mairie est souvent requise. Nos techniciens vous accompagnent dans ces démarches.",
  },
  {
    slug: "neuilly-sur-seine",
    name: "Neuilly-sur-Seine",
    dept: "92",
    depName: "Hauts-de-Seine",
    context: "Commune résidentielle haut de gamme bordant le Bois de Boulogne, Neuilly-sur-Seine concentre de nombreuses résidences de standing et hôtels particuliers. Les installations climatisation y nécessitent souvent une discrétion esthétique particulière. Nous réalisons régulièrement des installations gainables invisibles et des multisplits sur mesure pour les logements de grande surface.",
    faqQ: "Quelles sont les contraintes d'installation à Neuilly-sur-Seine pour les bâtiments anciens ?",
    faqA: "Neuilly-sur-Seine comporte plusieurs zones de protection patrimoniale. Pour les bâtiments en façade classée ou proche d'un monument, une autorisation de l'Architecte des Bâtiments de France peut être requise. Pour les résidences récentes, les contraintes sont celles de la copropriété. Nous étudions chaque cas lors de la visite technique gratuite.",
  },
  {
    slug: "versailles",
    name: "Versailles",
    dept: "78",
    depName: "Yvelines",
    context: "Ville royale des Yvelines, Versailles est classée patrimoine UNESCO. Le centre-ville historique est soumis à des règles d'urbanisme strictes (zone ABF). Les quartiers périphériques comme Saint-Louis, Montreuil ou les Chantiers offrent plus de flexibilité pour l'installation de climatisation. Nos techniciens connaissent parfaitement les contraintes locales du PLU versaillais.",
    faqQ: "La zone ABF de Versailles complique-t-elle l'installation d'une climatisation ?",
    faqA: "Dans le périmètre ABF de Versailles, toute installation visible depuis l'espace public nécessite l'accord de l'Architecte des Bâtiments de France. En pratique, les unités posées en cour intérieure ou sur des toitures non visibles sont acceptées. Nous réalisons un diagnostic préalable pour identifier les contraintes de votre adresse avant tout devis.",
  },
  {
    slug: "vincennes",
    name: "Vincennes",
    dept: "94",
    depName: "Val-de-Marne",
    context: "Aux portes de Paris et du Bois de Vincennes, Vincennes est une commune familiale très appréciée du Val-de-Marne. Le tissu urbain mêle immeubles anciens en copropriété et maisons individuelles. Les chaleurs estivales amplifiées par la minéralisation du bois en font une zone à forte demande pour la climatisation réversible, utilisée aussi en chauffage d'appoint l'hiver.",
    faqQ: "Peut-on installer une climatisation dans une maison individuelle à Vincennes ?",
    faqA: "Oui, à Vincennes les maisons individuelles peuvent accueillir une installation climatisation sans autorisation particulière si l'unité extérieure n'est pas visible depuis la voie publique. Pour les maisons mitoyennes ou les lotissements avec règlement de copropriété, il faut vérifier les conditions du règlement. Nous vous accompagnons dans ces vérifications.",
  },
  {
    slug: "creteil",
    name: "Créteil",
    dept: "94",
    depName: "Val-de-Marne",
    context: "Préfecture du Val-de-Marne, Créteil est une ville mixte alliant grands ensembles résidentiels, maisons pavillonnaires et zones commerciales actives. Le quartier du Lac et les tours du centre-ville nécessitent des approches d'installation spécifiques. Nous intervenons aussi bien dans les appartements en tour que dans les pavillons du secteur Est.",
    faqQ: "Intervenez-vous dans les tours d'appartements à Créteil ?",
    faqA: "Oui, nous avons une solide expérience dans les installations en grands ensembles à Créteil. Les contraintes techniques (hauteur, accès toiture, passage de gaines en cage d'ascenseur) sont maîtrisées par nos techniciens. L'accord du syndic de copropriété est requis pour les travaux en parties communes.",
  },
  {
    slug: "nanterre",
    name: "Nanterre",
    dept: "92",
    depName: "Hauts-de-Seine",
    context: "Ville en pleine transformation grâce au Grand Paris Express, Nanterre conjugue quartiers résidentiels, campus universitaire et zone d'affaires La Défense. Les logements y sont variés, des années 1970 aux programmes neufs. La proximité de La Défense génère une forte demande en climatisation pour locaux professionnels et appartements dans les tours.",
    faqQ: "Proposez-vous des solutions climatisation pour les bureaux et locaux professionnels à Nanterre ?",
    faqA: "Oui, nous intervenons fréquemment à Nanterre pour des installations en locaux professionnels et bureaux. Les systèmes VRV/VRF pour les open spaces et les cassettes de plafond pour les salles de réunion font partie de nos réalisations. Nous proposons des interventions en dehors des heures ouvrées pour minimiser les perturbations.",
  },
  {
    slug: "issy-les-moulineaux",
    name: "Issy-les-Moulineaux",
    dept: "92",
    depName: "Hauts-de-Seine",
    context: "Issy-les-Moulineaux est l'une des communes les plus dynamiques des Hauts-de-Seine, connue pour ses sièges de grands groupes médias et ses programmes immobiliers modernes. Le parc résidentiel neuf offre souvent des emplacements dédiés à la pose d'unités extérieures. Nos techniciens assurent des installations soignées dans les résidences de standing du Val-de-Seine.",
    faqQ: "Les résidences neuves à Issy-les-Moulineaux sont-elles prééquipées pour la climatisation ?",
    faqA: "Certains programmes neufs à Issy-les-Moulineaux prévoient des fourreaux et des emplacements en façade pour les unités extérieures. Si votre logement n'est pas prééquipé, nous réalisons l'installation complète avec un percement soigné et un calfeutrement parfait. Nous vérifions systématiquement le règlement de copropriété avant toute intervention.",
  },
  {
    slug: "levallois-perret",
    name: "Levallois-Perret",
    dept: "92",
    depName: "Hauts-de-Seine",
    context: "Commune la plus dense d'Europe, Levallois-Perret concentre des appartements en immeuble haussmannien et des résidences modernes. La densité et la chaleur urbaine renforcent le besoin en climatisation. Les toits-terrasses et les balcons privatifs offrent souvent des solutions d'installation sans contrainte de copropriété. Nos équipes connaissent bien les contraintes de cette ville très urbanisée.",
    faqQ: "Comment installer une climatisation dans un appartement sans balcon à Levallois-Perret ?",
    faqA: "Dans les appartements sans balcon à Levallois-Perret, plusieurs solutions existent : pose de l'unité extérieure sur le toit-terrasse, sur une cour intérieure ou sur des supports muraux en façade arrière. Chaque configuration est étudiée lors de la visite technique gratuite. Nous réalisons le passage de liaisons frigorifiques en gaine PVC pour un rendu esthétique.",
  },
  {
    slug: "montreuil",
    name: "Montreuil",
    dept: "93",
    depName: "Seine-Saint-Denis",
    context: "Montreuil, ville dynamique et diverse de Seine-Saint-Denis, connaît une forte croissance immobilière avec de nombreux programmes neufs dans le quartier Croix-de-Chavaux. Le parc ancien des Murs à Pêches et des quartiers populaires représente également une clientèle importante pour la climatisation réversible économique. Nos techniciens interviennent dans toute la commune.",
    faqQ: "Proposez-vous des climatisations économiques pour les logements anciens à Montreuil ?",
    faqA: "Oui, à Montreuil nous proposons des solutions adaptées à tous les budgets. Pour les logements anciens aux budgets serrés, le monosplit à partir de 1 500 € TTC reste la solution la plus accessible. Les aides CEE (jusqu'à 800 €) et la TVA réduite (10 % sur la pose d'une clim réversible, 5,5 % pour une PAC air-eau) pour les logements de plus de 2 ans permettent de réduire significativement le coût final.",
  },
  {
    slug: "saint-maur-des-fosses",
    name: "Saint-Maur-des-Fossés",
    dept: "94",
    depName: "Val-de-Marne",
    context: "Ville résidentielle de caractère en bord de Marne, Saint-Maur-des-Fossés est composée principalement de maisons individuelles et de pavillons avec jardin. C'est un terrain idéal pour les installations de climatisation multisplit et gainable. La présence de nombreuses maisons individuelles simplifie la pose des unités extérieures au sol ou en façade.",
    faqQ: "Quelle climatisation recommandez-vous pour une maison à Saint-Maur-des-Fossés ?",
    faqA: "Pour les maisons à Saint-Maur-des-Fossés, nous recommandons généralement un multisplit 2 à 4 têtes selon le nombre de pièces, ou un gainable si la maison dispose d'un faux-plafond ou de combles aménageables. L'unité extérieure peut être posée au sol dans le jardin pour une installation discrète. Nous réalisons un dimensionnement précis lors de la visite technique.",
  },
  {
    slug: "asnieres-sur-seine",
    name: "Asnières-sur-Seine",
    dept: "92",
    depName: "Hauts-de-Seine",
    context: "Ville en plein essor des Hauts-de-Seine, Asnières-sur-Seine combine anciens immeubles de rapport et programmes neufs de standing. La proximité de Paris et de La Défense attire des profils professionnels exigeants en matière de confort thermique. Nous réalisons régulièrement des installations dans les résidences récentes des bords de Seine.",
    faqQ: "Quel délai pour une installation climatisation à Asnières-sur-Seine ?",
    faqA: "Nous intervenons à Asnières-sur-Seine sous 48h après acceptation du devis. Pour les projets standards (monosplit ou multisplit jusqu'à 3 pièces), la pose est réalisée en 1 à 2 jours. Le devis gratuit est envoyé sous 24h après votre demande, avec ou sans visite préalable.",
  },
  {
    slug: "rueil-malmaison",
    name: "Rueil-Malmaison",
    dept: "92",
    depName: "Hauts-de-Seine",
    context: "Grande commune résidentielle des Hauts-de-Seine, Rueil-Malmaison mêle quartiers pavillonnaires avec jardins et zones d'affaires (Atrium). La présence d'un tissu pavillonnaire important facilite l'installation de climatisation en maison individuelle. Nous couvrons l'ensemble de la commune, du centre historique au quartier de La Jonchère.",
    faqQ: "Proposez-vous des installations climatisation pour les locaux professionnels à Rueil-Malmaison ?",
    faqA: "Oui, nous intervenons fréquemment dans la zone d'affaires de Rueil-Malmaison pour des installations en bureaux et locaux commerciaux. Nous proposons des contrats de maintenance annuelle adaptés aux entreprises avec intervention prioritaire sous 48h. Récupération de TVA possible pour les professionnels.",
  },
  {
    slug: "colombes",
    name: "Colombes",
    dept: "92",
    depName: "Hauts-de-Seine",
    context: "Troisième ville des Hauts-de-Seine par sa population, Colombes est une commune populaire et familiale. Le parc immobilier varié (maisons individuelles, immeubles des années 60-80, programmes neufs) offre une grande diversité de cas d'installation. Nos techniciens y réalisent aussi bien des monosplits pour les appartements que des multisplits pour les maisons.",
    faqQ: "Y a-t-il des aides spécifiques pour la climatisation à Colombes ?",
    faqA: "À Colombes, les aides nationales s'appliquent : TVA réduite (10 % sur la pose d'une clim réversible, 5,5 % pour une PAC air-eau) pour les logements de plus de 2 ans, CEE pour les PAC air-eau éligibles, MaPrimeRénov' selon vos revenus. Des aides locales des Hauts-de-Seine peuvent également être disponibles. Nos techniciens RGE vérifient votre éligibilité et gèrent les dossiers.",
  },
  {
    slug: "argenteuil",
    name: "Argenteuil",
    dept: "95",
    depName: "Val-d'Oise",
    context: "Première ville du Val-d'Oise, Argenteuil est une commune populaire en bord de Seine avec un important parc de logements sociaux et privés. La demande en climatisation y est forte, notamment dans les appartements des années 70 aux performances thermiques limitées. Nous proposons des solutions adaptées à tous les budgets pour les habitants d'Argenteuil.",
    faqQ: "Intervenez-vous dans les logements sociaux à Argenteuil ?",
    faqA: "Nous intervenons dans les logements privés à Argenteuil. Pour les logements HLM ou sociaux, l'accord du bailleur social est obligatoire avant toute installation. Nous pouvons vous aider à constituer le dossier de demande auprès de votre bailleur. Les copropriétés privées nécessitent l'accord de l'assemblée générale pour les travaux en parties communes.",
  },
  {
    slug: "vitry-sur-seine",
    name: "Vitry-sur-Seine",
    dept: "94",
    depName: "Val-de-Marne",
    context: "Vitry-sur-Seine, ville en pleine mutation du Val-de-Marne, est desservie par le Grand Paris Express. Le renouvellement urbain y génère de nombreux programmes neufs aux côtés d'un parc ancien important. Nous intervenons dans toute la commune pour des installations résidentielles et professionnelles, des ateliers d'artistes du bord de Seine aux appartements du centre.",
    faqQ: "La nouvelle ligne de métro améliore-t-elle la valeur d'une climatisation à Vitry-sur-Seine ?",
    faqA: "L'arrivée du Grand Paris Express à Vitry-sur-Seine revalorise le marché immobilier local. Une installation climatisation réversible augmente la valeur locative et la valeur à la revente d'un bien. Les acheteurs et locataires considèrent de plus en plus la climatisation comme un équipement standard, notamment pour les logements des années 70 peu performants thermiquement.",
  },
  {
    slug: "saint-denis",
    name: "Saint-Denis",
    dept: "93",
    depName: "Seine-Saint-Denis",
    context: "Ville emblématique de Seine-Saint-Denis, Saint-Denis est en pleine transformation avec les Jeux Olympiques 2024 et le Grand Paris Express. Les nouveaux programmes immobiliers côtoient des quartiers anciens. Nous intervenons pour toutes les typologies de logements et locaux professionnels de la ville, des appartements étudiants aux bureaux de la zone Plaine Commune.",
    faqQ: "Proposez-vous des installations climatisation pour les locaux professionnels dans la Plaine de Saint-Denis ?",
    faqA: "Oui, la zone Plaine de Saint-Denis est l'une de nos zones d'intervention principales pour les locaux professionnels, bureaux et commerces. Nous proposons des systèmes centralisés VRV/VRF pour les grands plateaux, des cassettes de plafond pour les salles de réunion et des monosplits pour les bureaux individuels. Devis rapide sur photos sans déplacement préalable.",
  },
  {
    slug: "courbevoie",
    name: "Courbevoie",
    dept: "92",
    depName: "Hauts-de-Seine",
    context: "Porte d'entrée de La Défense, Courbevoie est une ville mixte combinant immeubles résidentiels de standing et tours de bureaux. Les appartements avec vue sur La Défense sont particulièrement exposés aux apports solaires. Nous réalisons des installations sur mesure dans les résidences haut de gamme du quartier Charras et les appartements modernes de la ville basse.",
    faqQ: "Comment gérer la chaleur dans un appartement face aux tours de La Défense à Courbevoie ?",
    faqA: "Les appartements orientés vers La Défense à Courbevoie subissent des apports solaires amplifiés par les effets de miroir des immeubles de verre. Un monosplit ou multisplit réversible est la solution la plus efficace. Nous appliquons un coefficient d'exposition majoré dans notre calcul de puissance pour garantir un confort optimal même lors des canicules.",
  },
  {
    slug: "clamart",
    name: "Clamart",
    dept: "92",
    depName: "Hauts-de-Seine",
    context: "Ville verdoyante des Hauts-de-Seine à proximité de la forêt de Meudon, Clamart est appréciée pour sa qualité de vie résidentielle. Le parc immobilier est mixte, avec de nombreuses maisons individuelles dans les quartiers résidentiels et des copropriétés modernes. La végétation environnante peut tempérer les étés mais n'empêche pas les vagues de chaleur.",
    faqQ: "Quelle puissance de climatisation pour une maison à Clamart bien isolée ?",
    faqA: "Pour une maison bien isolée à Clamart, le calcul de puissance s'effectue sur la base de 35 W/m². Pour une maison de 100 m², comptez environ 3,5 kW total — soit un multisplit 2 ou 3 têtes selon le nombre de pièces à climatiser. Notre calculateur en ligne vous donne une estimation en 2 minutes.",
  },
  {
    slug: "antony",
    name: "Antony",
    dept: "92",
    depName: "Hauts-de-Seine",
    context: "Ville résidentielle du sud des Hauts-de-Seine, Antony est connue pour ses quartiers pavillonnaires et ses grandes résidences. La ville accueille aussi une importante population étudiante. Les maisons individuelles du plateau et les appartements de la ville basse représentent les deux principales typologies de nos interventions à Antony.",
    faqQ: "Proposez-vous des solutions climatisation pour les étudiants à Antony ?",
    faqA: "Pour les studios et petits appartements étudiants à Antony, le monosplit est la solution idéale à partir de 1 500 € TTC. Pour les locataires, l'accord du propriétaire est nécessaire. Certains propriétaires bailleurs choisissent d'installer la climatisation pour valoriser leur bien et réduire les charges énergétiques de leurs locataires.",
  },
  {
    slug: "massy",
    name: "Massy",
    dept: "91",
    depName: "Essonne",
    context: "Pôle technologique majeur de l'Essonne, Massy accueille de nombreuses entreprises high-tech et des quartiers résidentiels modernes. L'important parc tertiaire génère une forte demande pour la climatisation professionnelle. Nos techniciens interviennent à Massy pour des installations résidentielles dans les copropriétés récentes et des systèmes professionnels dans les zones d'activités.",
    faqQ: "Intervenez-vous en urgence à Massy pour les pannes de climatisation professionnelle ?",
    faqA: "Oui, nous intervenons en urgence à Massy pour les pannes de climatisation professionnelle sous 48h, parfois le jour même selon disponibilité. Pour les entreprises avec des besoins critiques de continuité (salles serveurs, espaces de vente), nous proposons des contrats de maintenance avec astreinte prioritaire.",
  },
  {
    slug: "evry-courcouronnes",
    name: "Évry-Courcouronnes",
    dept: "91",
    depName: "Essonne",
    context: "Préfecture de l'Essonne et ville nouvelle planifiée, Évry-Courcouronnes dispose d'un parc immobilier des années 70-80 énergivore qui bénéficie grandement de la climatisation réversible. La ville accueille des logements sociaux, des copropriétés privées et des zones d'activités. Les aides à la rénovation énergétique s'y appliquent pleinement.",
    faqQ: "Y a-t-il des aides spéciales pour rénover la climatisation dans les logements anciens à Évry ?",
    faqA: "Les logements anciens d'Évry-Courcouronnes des années 70 bénéficient pleinement des aides à la rénovation énergétique : TVA réduite (10 % sur la pose d'une clim réversible, 5,5 % pour une PAC air-eau), CEE, et MaPrimeRénov' pour les PAC air-eau. Ces aides peuvent représenter jusqu'à 30-40 % du coût total d'une installation PAC. Nos techniciens RGE gèrent les dossiers de A à Z.",
  },
  {
    slug: "meaux",
    name: "Meaux",
    dept: "77",
    depName: "Seine-et-Marne",
    context: "Sous-préfecture de Seine-et-Marne, Meaux est une ville à taille humaine à moins d'une heure de Paris. Le bassin meldois connaît des étés chauds et secs. Le parc immobilier mêle maisons anciennes en centre-ville, pavillons en périphérie et copropriétés modernes. Nous intervenons à Meaux et dans tout le nord-est de la Seine-et-Marne.",
    faqQ: "Intervenez-vous dans toute la Seine-et-Marne depuis Meaux ?",
    faqA: "Oui, nos techniciens couvrent l'ensemble du département 77, dont Meaux et sa région. Les délais d'intervention depuis notre zone principale (Paris et proche couronne) peuvent être légèrement plus longs (48-72h) selon les disponibilités. Le devis gratuit est établi sous 24h et la visite technique peut être réalisée à distance sur photos.",
  },
  {
    slug: "melun",
    name: "Melun",
    dept: "77",
    depName: "Seine-et-Marne",
    context: "Préfecture de Seine-et-Marne, Melun est la ville principale du 77 avec un centre historique inscrit au patrimoine. Le bassin mellunais connaît des étés continentaux avec des températures élevées. Les maisons individuelles périphériques et les appartements du centre-ville sont les principales typologies de notre clientèle melunaise.",
    faqQ: "Combien coûte une installation climatisation à Melun par rapport à Paris ?",
    faqA: "Les tarifs d'installation à Melun sont identiques à ceux pratiqués en région parisienne. Des frais de déplacement peuvent s'appliquer selon la distance, mais sont offerts sur devis accepté. La grille tarifaire reste : monosplit à partir de 1 500 € TTC, multisplit à partir de 2 800 € TTC, pose incluse.",
  },
];

export function getVilleBySlug(slug: string): Ville | undefined {
  return VILLES.find((v) => v.slug === slug);
}
